export const tableHeader = [
  {
    id: "1",
    buttonName: "#",
    sortName: "number",
    isActive: true,
    sortDown: true,
    isVisible: true,
  },
  {
    id: "2",
    buttonName: "Ім’я",
    sortNmae: "clientName",
    isActive: false,
    sortDown: true,
    isVisible: true,
  },
  {
    id: "3",
    buttonName: "Тип техніки",
    sortNmae: "appliance",
    isActive: false,
    sortDown: true,
    isVisible: true,
  },
  {
    id: "4",
    buttonName: "Модель",
    sortNmae: "model",
    isActive: false,
    sortDown: true,
    isVisible: true,
  },
  {
    id: "5",
    buttonName: "Дата прийняття",
    sortNmae: "date",
    isActive: false,
    sortDown: true,
    isVisible: true,
  },
  {
    id: "6",
    buttonName: "Сума до сплати",
    sortNmae: "price",
    isActive: false,
    sortDown: true,
    isVisible: true,
  },
  {
    id: "7",
    buttonName: "Номер телефона",
    sortNmae: "phone",
    isActive: false,
    sortDown: true,
    isVisible: false,
  },
  {
    id: "8",
    buttonName: "Статус",
    sortNmae: "status",
    isActive: false,
    sortDown: true,
    isVisible: true,
  },
];
